dist: trusty
sudo: required
addons:
        apt:
                update: true
services:
        - docker
before_install:
        - cd data/mssql && sh install-drivers.sh && cd ../../
        - cd data/adw && sh build-image.sh && sh restore-db.sh && cd ../../
        - cd data/ds2 && sh build-image.sh && sh run-image.sh && ./check-health.sh && cd ../../

language: python
python:
        - "3.6"
install:
        - pip install -r requirements.txt
        - pip install -r requirements_test.txt
script:
        - coverage run --source=eddytools setup.py test
after_success:
        - coveralls
