dist: trusty
sudo: required
addons:
        apt:
                update: true
services:
        - docker
before_install:
        - sudo apt-get install freetds-dev
        - cd data/adw && ./build-image.sh && ./restore-db.sh && cd ../../
        - cd data/ds2 && ./build-image.sh && ./run-image.sh && ./check-health.sh && cd ../../

language: python
python:
        - "3.6"
install:
        - pip install -r requirements.txt
        - pip install -r requirements_test.txt
script:
        - coverage run --source=eddytools setup.py test
after_success:
        - coveralls
