sudo: required
services:
        - docker
before_install:
        - cd data && sh build-image.sh && sh run-image.sh

language: python
python:
        - "3.6"
install:
        - pip install -r requirements.txt
        - pip install -r requirements_test.txt
script:
        - python -m pytest test/
